### ISSUE TITLE
Add phone number, social security number, state, http code datatype detection

### ISSUE THREAD

**Issue by argenisleon** [hi-primus/optimus#1048]
Implement detection for:
- [x] phone number 
- [x]  social security number
- [x] state
- [x] http code

**Comment by lighthouseahoy** [comment]
Where the detected formats are country specific, please ensure the objects are labelled as such.  The 303-555-2021 format is indicative of a +13035552021 phone number, but is specific to NANP.  The WA state code is a US and an AU state code but they are different places.

**Comment by argenisleon** [comment]
Hi @lighthouseahoy,

Have you checked https://github.com/daviddrysdale/python-phonenumbers? 

What functionality from this library would like to see in Optimus?

**Comment by lighthouseahoy** [comment]
That looks like a thorough library.  I would be most interested in simple validation.  Which country is it in (blank on any error)?  [Sorry, I worry when I see phone number validation because it is a lot more complicated than people realise.]
