### ISSUE TITLE
Batching to improve Profiler performance

### ISSUE THREAD

**Issue by argenisleon** [hi-primus/optimus#322]
Right now one of the main profiler bottlenecks is that histogram is calculated in a pass for every column. It seems that with the help of UDAF we can gain significant performance. The only way to use it is via Scala. [Here](https://deepsense.ai/improve-aggregate-performance-with-batching/) is a reference or how it can be implemented.

**Comment by akarsh3007** [comment]
@argenisleon Can I take this issue? can you please point me to the right codebase?

**Comment by argenisleon** [comment]
Hi @akarsh3007,

Here is calculated the histogram for every column in the dataframe https://github.com/ironmussa/Optimus/blob/9c25a4152f4856b4b0d6c7316f328959c7a30d9d/optimus/profiler/profiler.py#L383

As you can see there are different functions to calculate the histogram depending on the column datatype numeric, categorical/array or date.

The article pointed in the issue have a link to the GitHub code base (in case you miss it) https://github.com/Ajk4/aggregators_batching

Anything more I could help?

**Comment by akarsh3007** [comment]
This looks good, I will start working on this. Just one question are we planning to register this UDAF as `spark.udf.registerJavaUDAF(function)` to use in here ?

**Comment by argenisleon** [comment]
Hi @akarsh3007,
I am not sure but registerJavaUDAF(function) seems the way to go. Look at this https://www.codota.com/code/java/classes/org.apache.spark.sql.UDFRegistration

**Comment by argenisleon** [comment]
Hi @akarsh3007,

Are you still planning to work on this?

**Comment by akarsh3007** [comment]
@argenisleon  Hi, yeah I am planning to work on this, I have been a little busy, I will start this over the coming weekend.  Thanks

**Comment by pallav1991** [comment]
@argenisleon 
Is there any update on this??
I have one more issue that there at times when i have seen the profiler returning unique_count value wrong. I am not sure this issue is at your end or at my end. but can you look at this once, if possible. 

sorry I am tight at my schedule or else I would have looked at it.

**Comment by argenisleon** [comment]
Pyspark example
https://ragrawal.wordpress.com/2015/08/25/pyspark-top-n-records-in-each-group/

Scale Implementation
https://github.com/Ajk4/aggregators_batching/blob/master/src/main/scala/io/deepsense/deeplang/utils/aggregators/HistogramAggregator.scala

**Comment by argenisleon** [comment]
Because we are using koalas as backend this is no longer needed.
