### ISSUE TITLE
Add Dask as Backend

### ISSUE THREAD

**Issue by argenisleon** [hi-primus/optimus#728]
WIP here https://github.com/ironmussa/Optimus/tree/develop-3.0

- [x] Create aggregation Layer
- [x] Port aggregation/profiling functions
- [x] Track metadata transformation in dask dataframes
- [x] Port rows and cols functions
- [x] Port JDBC Layer
- [x] Port ML functions

**Comment by argenisleon** [comment]
@FavioVazquez, maybe you want to start looking into the ML functions?

**Comment by FavioVazquez** [comment]
I'm on it @argenisleon
