### ISSUE TITLE
Support for Alluxio Reads

### ISSUE THREAD

**Issue by avinish1** [hi-primus/optimus#866]
Hi,

I am not sure if I can read files on alluxio via the optimus object.

File paths are of the form **alluxio://<file_URL_on Alluxio>**

Generally this could be done by **spark**.read(<**Alluxio_URL**>) as mentioned earlier with "**spark**" as the sparkContext object.

Issue is if thats the case then I would have to read it with a seperate spark context and then run a new optimus sparkContext for developing any kind of a pipeline.

I may be completely off but request you to guide me.

**Comment by argenisleon** [comment]
Hi @avinish1,

You have multiple options:

First option: If you already create and spark session you can pass a session to Optimus like this.
```from pyspark.sql import SparkSession
from optimus import Optimus

spark = SparkSession.builder.appName('optimus').getOrCreate()
op= Optimus(spark)
```

Second option: is to load the Alluxio jar in Optimus like this:

```
op= Optimus(repositories = "myrepo", packages="org.apache.spark:spark-avro_2.12:2.4.3", jars="my.jar", driver_class_path="this_is_a_jar_class_path.jar", verbose= True)
```

Third Option: we can add Optimus Alluxio support? I could help you to work on this.

**Comment by avinish1** [comment]
Aplologize for the delayed response.

Thanks for the tip, I have been trying to install it, will open a new issue that I am facing.

Regarding the third option you mentioned, I will try to work on it, could you guide me.

**Comment by argenisleon** [comment]
@avinish1 I create a small guide here. https://github.com/ironmussa/Optimus/blob/master/README_for_devs.md#create-a-new-database-driver

Maybe you could open a pull request so I can help if you need it?

**Comment by argenisleon** [comment]
Hi @avinish1,

I think this could be a good addition to Optimus. Maybe you could work in testing and make the 5 queries needed to implement the driver, and I could write the codebase to make it work?

**Comment by argenisleon** [comment]
Out of scope at the moment.
