### ISSUE TITLE
Use Poetry so new developers can contribute easier

### ISSUE THREAD

**Issue by MrPowers** [hi-primus/optimus#947]
Thanks for continuing to do great work on this project!

**Is your feature request related to a problem? Please describe.**
I'd like to be able to clone this repo and easily install all the project dependencies in a virtual environment.  Poetry makes this easy, [as described in this blog post](https://mungingdata.com/pyspark/poetry-dependency-management-wheel/) ;)

**Describe the solution you'd like**
Migrate from the pip [requirements.txt](https://github.com/ironmussa/Optimus/blob/master/requirements.txt) approach to the Poetry project organization.

I'd be good to create a section of the README that'd help folks that want to contribute to the project.  Instructions on how to get their dev environment setup and how to run tests.

**Describe alternatives you've considered**
pipenv is another alternative, but seems like more of the community is going with Poetry.

**Comment by argenisleon** [comment]
Hey @MrPowers :),

Thanks for the improvement request. I am going to take a look at Poetry. Optimus 3.0 is going to use conda because rapids do not support pip. Any experience with Poetry and conda ?

**Comment by MrPowers** [comment]
@argenisleon - Looks like [conda & poetry are compatible](https://github.com/python-poetry/poetry/issues/105).  I will try it out when I have some free time and report back!

**Comment by argenisleon** [comment]
Hi @MrPowers, finally we decided to stay with pip. Would you like to go ahead with this?

**Comment by argenisleon** [comment]
Poetry added in b46e3d0d71f3981a4ebbf061af2050720684f72a

**Comment by MrPowers** [comment]
@argenisleon - sweet you got this added, thank you!!
